# Generated by Django 4.0.5 on 2022-07-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='movie')),
                ('path_to_file', models.FilePathField()),
                ('movie_id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
